DROP DATABASE IF EXISTS TP2_CERVO_MARIABELEN;
CREATE DATABASE TP2_CERVO_MARIABELEN;
USE TP2_CERVO_MARIABELEN;

CREATE TABLE interests (
	id TINYINT(2) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	interest VARCHAR(50) NOT NULL UNIQUE
) ENGINE = innoDB;

CREATE TABLE users (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(75),
	lastname VARCHAR(75),
	email VARCHAR(255) NOT NULL UNIQUE,
	password VARCHAR(255) NOT NULL,
	photo VARCHAR(40) NOT NULL DEFAULT 'default.jpg',
	startdate DATETIME NOT NULL,
	location VARCHAR(255),
	birthday DATE NOT NULL,

	fkinterest TINYINT(2) UNSIGNED,

	FOREIGN KEY(fkinterest) REFERENCES interests(id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE = innoDB;

CREATE TABLE categories (
	id TINYINT(1) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	category VARCHAR(20) NOT NULL UNIQUE
) ENGINE = innoDB;

CREATE TABLE posts (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	photo VARCHAR(40) DEFAULT 'default.png',
	title VARCHAR(100) NOT NULL,
	location VARCHAR(255) NOT NULL,
	description VARCHAR(255) NOT NULL,
	startdate DATETIME NOT NULL,
	
	fkuser INT UNSIGNED NOT NULL,
	fkcategory TINYINT(1) UNSIGNED NOT NULL,
  	
  	FOREIGN KEY(fkuser) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(fkcategory) REFERENCES categories(id) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE = innoDB;

CREATE TABLE user_comments_post (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	fkuser INT UNSIGNED NOT NULL,
	fkpost INT UNSIGNED NOT NULL,
	startdate DATETIME NOT NULL,
	comment VARCHAR(255) NOT NULL,

	FOREIGN KEY(fkuser) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(fkpost) REFERENCES posts(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = innoDB;